version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: the raw dataset
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id

        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness: 
          warn_after: {count: 90, period: day}
        
        columns:
          - name: date_date
            description: date of purchase

          - name : orders_id
            description: foreign key to ship
            tests:
              - not_null


          - name : pdt_id
            description: foreign key to product
            tests: 
              - not_null
              


          - name: revenue
            description : the quantity of products purchased for a given order


          - name: quantity
            description: number of products per order

          - name: unique_orders_pdt
            description: Ensure combination of orders_id and pdt_id is unique
            
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns: ["orders_id", "pdt_id"]
          

      - name: product
        identifier: raw_gz_product
        description: products of Greenweez / we have a row per product_id and its purchase cost
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null

          - name: purchase_price
            description: price of each purchase

      - name: ship
        identifier: raw_gz_ship
        description: ship details of Greenweez / we have a row per order_id and its costs
        columns:
          - name: orders_id
            description: primary key, order id 
            tests:
              - unique
              - not_null

          - name: shipping_fee
            description: the price the customer pays for shipping

          - name: logcost
            description: cost log preparing parcel


          - name: ship_cost
            description: ship costs
