version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
            tests:
              - not_null
          
          - name : orders_id
            description: order id
            tests:
              - not_null

          - name : pdt_id
            description: product id
            tests:
              - not_null

          - name: revenue
            description : price per order
            tests :
              - not_null

          - name: quantity
            description: number of products per order
            tests:
              - not_null

      - name: product
        identifier: raw_gz_product
        description: products of Greenweez / we have a row per product_id and its purchase cost
        columns:
          - name: products_id
            description: primary key, we have a row per product_id and its purchase cost
            tests:
              - not_null

          - name: purchSE_price
            description: price of each purchase
            tests:
              - not_null

      - name: ship
        identifier: raw_gz_ship
        description: ship details of Greenweez / we have a row per order_id and its costs
        columns:
          - name: orders_id
            description: primary key, order id 
            tests:
              - not_null

          - name: shipping_fee
            description: shippings fee 
            tests:
              - not_null
          
          - name: logcost
            description: cost log
            tests:
              - not_null

          - name: ship_cost
            description: ship costs
            tests:
              - not_null