version: 2

sources:
  - name: gz_raw_data
    description: source raw
    tables:
      - name: raw_gz_product
        description: gz products
      - name: raw_gz_sales
        description: sales
      - name : raw_gz_ship
        description: ship

  - name: dbt_lknoery
    description: "Source contenant les marges des commandes"
    tables:
      - name: int_orders_margin
        description: "Table contenant les informations des marges des commandes"
      - name: int_orders_operational
        description: orders operational
        columns:
          - name: orders_id
            description: "ID de la commande"
            tests:
              - unique
              - not_null
          - name: date_date
            description: "Date de la commande"
            tests:
              - not_null
          - name: operational_margin
            description: "Marge opérationnelle de la commande"
          - name: quantity
            description: "Quantité de produits commandés"
          - name: revenue
            description: "Revenu généré par la commande"
          - name: purchase_cost
            description: "Coût d'achat de la commande"
          - name: margin
            description: "Marge brute de la commande"
          - name: shipping_fee
            description: "Frais de livraison associés à la commande"
          - name: logcost
            description: "Coût logistique de la commande"
          - name: ship_cost
            description: "Coût d'expédition de la commande"
      - name: int_sales_margin
        description: sales margin
